INSERT INTO pessoa(nome, cidade, cep) VALUES('Sr. Vinícius Casa Grande', 'Siqueira de da Rosa', '97130-909');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Samuel Castro', 'Ramos de Borges', '93982056');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Srta. Maria Júlia Araújo', 'Freitas', '27540-538');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Melina Albuquerque', 'Silva de Barbosa', '57311515');
INSERT INTO pessoa(nome, cidade, cep) VALUES('José Pedro Monteiro', 'Costa da Mata', '27582933');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Samuel Brito', 'Sousa da Mata', '71606-023');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Sra. Agatha Cunha', 'Dias da Prata', '87624450');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Isadora Câmara', 'Fonseca do Sul', '98517-032');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Maria Clara Rios', 'Mendonça', '04916-568');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Beatriz Garcia', 'Machado', '21001-771');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Fernando Aragão', 'Vieira', '64836888');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Rafaela Azevedo', 'Viana da Prata', '02833017');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Sra. Sophia Garcia', 'da Conceição da Mata', '93895-661');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Yago Viana', 'Souza de Montenegro', '47234-621');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Vinícius Pacheco', 'da Conceição', '22579786');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Nicole da Mata', 'Cardoso do Sul', '26659018');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Sra. Laís Barbosa', 'Vasconcelos do Norte', '70426-384');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Isadora Marques', 'Rezende do Oeste', '06562142');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Bella Machado', 'Martins', '61616707');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Dra. Lara Nogueira', 'Costa do Amparo', '40130484');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Mathias da Cunha', 'Costela do Oeste', '75496-544');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Sr. Noah Machado', 'Fernandes', '90203-608');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Elisa Porto', 'Cavalcante do Sul', '63934257');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Luiz Henrique Caldeira', 'Montenegro', '43204-371');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Srta. Elisa Vieira', 'Cavalcante do Amparo', '49249-215');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Ana Cecília Montenegro', 'Almeida', '01988-712');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Rhavi Sampaio', 'Peixoto', '10282867');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Carolina Cavalcanti', 'Pastor do Galho', '44517979');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Francisco Brito', 'da Costa de Caldeira', '76703-330');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Fernando Andrade', 'Garcia das Flores', '39135945');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Ana Liz Nogueira', 'Barros', '82031-249');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Samuel Mendonça', 'Rios das Pedras', '82605-265');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Rodrigo Pereira', 'Cirino', '71290086');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Fernanda da Cruz', 'Aparecida do Amparo', '45513-591');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Esther Correia', 'Pacheco de Fogaça', '51542-264');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Davi Miguel Rios', 'Ramos do Amparo', '85844-509');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Sra. Bianca Nascimento', 'Silveira do Oeste', '54151-103');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Dr. Liam da Cruz', 'Cunha das Pedras', '21182-996');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Manuella Novaes', 'Siqueira', '78913-190');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Brayan das Neves', 'Sales das Pedras', '22239372');
INSERT INTO pessoa(nome, cidade, cep) VALUES('João Guilherme da Luz', 'Novaes de Carvalho', '11349-899');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Maria Fernanda Cirino', 'Rezende do Campo', '95046977');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Sr. Caio da Mota', 'da Rocha', '28282-021');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Emanuelly Lopes', 'Mendonça', '68372711');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Samuel Cassiano', 'Pacheco do Campo', '74747798');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Dr. Cauê Guerra', 'Costa Alegre', '88483757');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Maria Julia Monteiro', 'Cassiano de Melo', '39228952');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Juliana Costela', 'Costa', '74013172');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Bella Siqueira', 'da Luz da Serra', '95876-883');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Yuri Sampaio', 'Campos', '32221-745');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Ravy Guerra', 'Silva Grande', '91100110');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Luiz Otávio Fernandes', 'Pereira de Correia', '46894225');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Marina Novaes', 'Novais', '71736152');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Elisa Câmara', 'Ribeiro', '92563162');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Nathan Nunes', 'Jesus', '69850-479');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Theo Melo', 'Andrade Paulista', '31708-180');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Maitê Rocha', 'Barros Paulista', '23508876');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Maria da Paz', 'Rodrigues', '88173235');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Isaac Montenegro', 'Costela de das Neves', '69445940');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Sra. Stella Carvalho', 'Silveira', '93807782');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Catarina Rios', 'Casa Grande', '09367522');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Benício Sampaio', 'Brito de Nunes', '42829-843');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Lucas Gabriel Gomes', 'Vargas do Norte', '29322-788');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Davi Lucca Silva', 'Fonseca do Sul', '03457776');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Mateus Sá', 'Dias', '50174-493');
INSERT INTO pessoa(nome, cidade, cep) VALUES('João Felipe Rios', 'da Cruz das Pedras', '32763763');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Daniela Aragão', 'Almeida de Costela', '87797-495');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Sara Câmara', 'Farias do Sul', '88539799');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Clarice Fogaça', 'Macedo de Goiás', '42635-846');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Maria Alice Cassiano', 'Montenegro de Vasconcelos', '09575786');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Ana Liz Silveira', 'Nunes Alegre', '66489517');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Anna Liz Borges', 'Borges', '21242341');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Ryan Souza', 'Leão', '54337-059');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Isaac Sales', 'Teixeira', '74314394');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Srta. Maria Luiza Araújo', 'Barros de Minas', '93602-719');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Lunna Rodrigues', 'da Paz do Norte', '55374865');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Ana Lívia Teixeira', 'Sampaio', '00733-088');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Eloah Cirino', 'Farias', '04121-162');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Ana Laura Marques', 'Barros do Oeste', '99012960');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Sra. Laís Pereira', 'da Luz de Sá', '48089-273');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Srta. Beatriz Pinto', 'Nogueira das Flores', '13940038');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Luiz Fernando Caldeira', 'Pereira da Prata', '46850-545');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Cauê Montenegro', 'da Luz', '97663-524');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Clara Lima', 'Porto', '74760326');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Thomas Ferreira', 'Cassiano', '90432-820');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Sr. Arthur Gabriel Pereira', 'Rodrigues de Goiás', '20625-528');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Fernando Moura', 'Dias de Pimenta', '73953-143');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Emanuel Vieira', 'Oliveira do Sul', '03487317');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Gabriela da Rocha', 'da Mata', '20698-906');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Luiz Miguel Rocha', 'Sá das Pedras', '60847671');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Mateus da Rosa', 'Monteiro Verde', '84647-912');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Maysa Moraes', 'Camargo', '37676935');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Vitória Novaes', 'Dias do Sul', '91503-692');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Srta. Clara Porto', 'Correia', '12819425');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Manuela Mendes', 'Dias', '33509396');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Luna da Conceição', 'Costa de Costela', '99371-508');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Caio Pacheco', 'Nogueira de Marques', '99857726');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Thales Aragão', 'Ferreira das Flores', '54809-734');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Melissa da Mata', 'Borges do Sul', '62620-831');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Eloá Jesus', 'Dias do Oeste', '83856956');
