create table t_pix(
    id_pix number generated by default as identity,
    chave varchar2(50) not null,
    nome varchar2(100),
    banco varchar(50) not null,
    agencia varchar(10) not null,
    conta varchar(20) not null,
    primary key(id_pix)
);

insert into t_pix(chave, nome, banco, agencia, conta)
    values('profeduardo@fiap.com.br', 'Edu', 'Brasil', '0001', '0002');
insert into t_pix(chave, nome, banco, agencia, conta)
    values('gondo@gmail', 'Edu', 'C6', '0001', '000043');