CREATE TABLE cliente(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nm_cliente VARCHAR2(100),
    cpf VARCHAR2(20),
    tel_cliente VARCHAR(20),
    PRIMARY KEY(id)
);

CREATE TABLE endereco(
    pessoa_id NUMBER,
    cep VARCHAR2(15),
    logradouro VARCHAR2(100),
    nr_end VARCHAR2(15),
    bairro VARCHAR2(30),
    cidade VARCHAR2(30),
    complemento VARCHAR2(15),
    uf VARCHAR2(2),
    FOREIGN KEY (pessoa_id) REFERENCES cliente(id)
);

CREATE TABLE conta(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    tipo VARCHAR2(20),
    numero VARCHAR2(10),
    senha VARCHAR2(100),
    saldo NUMBER(10,2),
    cliente_id NUMBER,
    PRIMARY KEY(id),
    FOREIGN KEY (cliente_id) REFERENCES cliente(id)
);

CREATE TABLE transacao(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    valor NUMBER(10,2),
    data_hora TIMESTAMP,
    contraparte VARCHAR2(100),
    tipo VARCHAR2(50),
    conta_id NUMBER,
    PRIMARY KEY(id),
    FOREIGN KEY (conta_id) REFERENCES conta(id)
);

CREATE SEQUENCE sq_numero START WITH 1000 INCREMENT BY 1;