CREATE TABLE time(
    id number generated by default as identity,
    nome varchar(100),
    vitorias number default 0,
    empates number default 0,
    derrotas number default 0,
    gols_pro number default 0,
    gols_sof number default 0,
    primary key(id)
);

CREATE TABLE t_partida(
    id NUMBER PRIMARY KEY,
    mandante_id NUMBER,
    gols_mandante NUMBER,
    visitante_id NUMBER,
    gols_visitante NUMBER,
    FOREIGN KEY(mandante_id) REFERENCES time(id),
    FOREIGN KEY(visitante_id) REFERENCES time(id)
);